version: "3.1"
services:

  postgresdb:
    container_name: petpostgres
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: petdoctordb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1qaz2wsx

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    restart: on-failure
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/kafka-logs
#  kafka:
#    image: wurstmeister/kafka:2.13-2.6.0
#    container_name: kafka
#    hostname: kafka
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#      - "9101:9101"
#    environment:
#      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTER:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#      KAFKA_LISTENERS: INTERNAL://kafka:29092,OUTER://localhost:9092
#      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,OUTER://localhost:9092
#      KAFKA_JMX_PORT: 9101
#      KAFKA_JMX_HOSTNAME: localhost
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
#      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
#      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
#      KAFKA_HOST_NAME: localhost
#      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
#      KAFKA_LOG_DIRS: /kafka/kafka-logs


#  employee-service:
#    container_name: employee-service
#    image: employee-service
#    build:
#      context: ../EmployeeService
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgresdb
#      - kafka
#    restart: on-failure
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://petpostgres:5432/petdoctordb
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: 1qaz2wsx
#      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
#
#  enrollment-service:
#    container_name: enrollment-service
#    image: enrollment-service
#    build:
#      context: ../EnrollmentService
#      dockerfile: Dockerfile
#    ports:
#      - "8081:8081"
#    depends_on:
#      - postgresdb
#      - kafka
#    restart: on-failure
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://petpostgres:5432/petdoctordb
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: 1qaz2wsx
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
